## Homework - Problem 20

`xgboost_data2.csv`를 이용한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- `n_estimators=100`
- `learning_rate=0.1`

`max_depth`를 다음과 같이 변경하여 XGBoost를 Training한다.

`1, 2, 3, 5, 8`

다음 질문에 답하시오.

- 각 `max_depth`의 Test Accuracy를 소수점 셋째 자리까지 적으시오.
- 가장 높은 Test Accuracy를 보인 `max_depth`를 모두 적으시오.

답만 제출하시오.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split

In [5]:
import xgboost
xgboost.__version__

'3.4.1'

In [8]:
df = pd.read_csv('../Input/xgboost_data2.csv')
display(df.head())

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,-1.749765,-0.057433,-1.876946,1.783806,-1.354365,-0.087486,0.215454,-0.325999,0.711811,-0.045052,0
1,0.342680,-0.524517,0.889231,0.654023,-1.111521,0.643354,-0.869856,-1.178352,1.382963,-0.116582,0
2,1.153036,0.389762,-0.317945,-0.674075,0.771164,-1.059304,0.260657,-0.139788,0.405432,-0.162347,0
3,-0.252436,-1.891523,-0.476688,-0.874858,-0.793235,0.651638,0.714854,-0.881230,-1.068276,0.232415,1
4,0.981321,-1.422653,0.960474,-1.007713,0.815447,0.639285,0.479142,-1.176153,1.655798,2.044957,0

In [ ]:
X = df.drop(
    columns=["y"]
)

y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Data:", X_train.shape)
print("Test Data:", X_test.shape)

Training Data: (1600, 10)
Test Data: (400, 10)

In [18]:
acs = pd.DataFrame(
    columns=["max_depth", "accuracy"]
)

max_depths = [1, 2, 3, 4, 5]
count = 0

for depth in max_depths:
    model = XGBClassifier(
        random_state=42,
        n_estimators=100,
        max_depth=depth,
        learning_rate=0.1,
    )

    model.fit(
        X_train,
        y_train
    )

    score = model.score(
        X_test,
        y_test
    )



    acs.loc[count] = [depth, f"{score:0.3f}"]
    count += 1

display(acs)

   max_depth accuracy
0          1    0.762
1          2    0.775
2          3    0.807
3          4    0.835
4          5    0.835