## Assignment - 문제 12

`Input/lasso_data2.csv`를 이용하여 Lasso Regression을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- $\alpha = 0.01,\;0.1,\;1$

다음 질문에 답하시오.

- $\alpha=0.01$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=0.1$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=1$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=0.1$일 때 Weight가 0인 Feature Name을 모두 적으시오.
- 세 Lasso Models 중 Test MSE가 가장 작은 $\alpha$와 그 Test MSE를 소수점 셋째 자리까지 적으시오.

답만 제출하시오.

In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv('../Input/lasso_data2.csv')

In [3]:
X = df.drop(columns=["y"])
y = df["y"]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



display(df.head())

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,0.434049,-0.829093,-4.393303,-0.901535,4.588431,-4.722677,-4.568725,-0.441516,3.869059,-0.960351,-34.910058
1,-2.216306,1.955910,4.498369,-2.929594,4.110640,-1.177627,4.268489,-0.697097,-4.386685,0.901040,80.785495
2,-0.754824,-0.751528,1.086590,4.560227,-3.803252,4.532509,-0.703233,-0.943319,-1.327789,-0.009014,-28.781715
3,3.447761,3.581142,1.720027,-0.939888,-3.855314,-2.778015,1.309861,4.463605,3.471495,1.598288,58.161090
4,-4.952811,3.469325,-0.372265,2.168801,4.969650,-1.948739,-4.042762,-3.275777,-0.039060,4.016900,0.301579

In [4]:
linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)

linear_weights = pd.DataFrame({
    "Feature": X.columns,
    "Weight": linear_model.coef_
})

display(linear_weights)

print(
    "Test MSE:",
    mean_squared_error(
        y_test,
        linear_model.predict(X_test)
    )
)

  Feature    Weight
0      x1  0.104740
1      x2  6.818677
2      x3 -0.173986
3      x4 -5.992371
4      x5  0.171214
5      x6  0.053286
6      x7  8.888501
7      x8 -0.030175
8      x9  0.146533
9     x10  4.061595

Test MSE: 11.72153747000301

In [5]:
alphas = [0.01, 0.1, 1]
# alphas = [0.1]
for alpha in alphas:
    lasso_model = Lasso(
        alpha=alpha
    )

    lasso_model.fit(
        X_train,
        y_train
    )

    lasso_weights = pd.DataFrame({
        "Feature": X.columns,
        "Weight": lasso_model.coef_
    })

    display(lasso_weights)

    print(
        "Test MSE:",
        mean_squared_error(
            y_test,
            lasso_model.predict(X_test)
        )
    )

  Feature    Weight
0      x1  0.102875
1      x2  6.817584
2      x3 -0.172665
3      x4 -5.990788
4      x5  0.170143
5      x6  0.052013
6      x7  8.887027
7      x8 -0.028072
8      x9  0.145564
9     x10  4.060645

Test MSE: 11.71987268776042

  Feature    Weight
0      x1  0.085488
1      x2  6.806844
2      x3 -0.160829
3      x4 -5.976145
4      x5  0.160335
5      x6  0.040541
6      x7  8.873811
7      x8 -0.008842
8      x9  0.137225
9     x10  4.052195

Test MSE: 11.722231406800265

  Feature    Weight
0      x1  0.000000
1      x2  6.718851
2      x3 -0.055387
3      x4 -5.860287
4      x5  0.064901
5      x6  0.000000
6      x7  8.758075
7      x8  0.000000
8      x9  0.041104
9     x10  3.949210

Test MSE: 12.741776587599604