## Homework - Problem 13

`Input/logistic_data3.csv`를 이용하여 Logistic Regression을 수행한다.

다음 조건을 사용한다.

- Input Features: `x1`, `x2`
- Output: `y`
- `test_size=0.2`
- `random_state=42`

다음 질문에 답하시오.

- 학습된 `x1`의 Weight를 소수점 셋째 자리까지 적으시오.
- 학습된 `x2`의 Weight를 소수점 셋째 자리까지 적으시오.
- 학습된 Bias를 소수점 셋째 자리까지 적으시오.
- Test Data의 Accuracy를 소수점 셋째 자리까지 적으시오.
- Test Data의 첫 번째 Sample에 대한 $P(y=1|X)$를 소수점 셋째 자리까지 적으시오.
- 위 Probability를 Threshold 0.5를 사용하여 분류한 Class를 적으시오.

답만 제출하시오.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('../Input/logistic_data3.csv')

display(df.head())

         x1        x2  y
0 -3.499531 -1.096985  1
1  0.685361 -0.105270  0
2  2.306072  6.346781  1
3 -0.504872  6.668407  1
4  1.962642  3.206744  1

In [3]:
# Input과 Output
X = df[["x1", "x2"]]
y = df["y"]

# Train / Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Logistic Regression Model
model = LogisticRegression()

# Training
model.fit(
    X_train,
    y_train
)

print("Weight:", model.coef_)
print("Bias:", model.intercept_)

Weight: [[-0.99875743  1.69743353]]
Bias: [-0.97684969]

In [4]:
model.accuracy = model.score(X_test, y_test)
print("Accuracy:", model.accuracy)

Accuracy: 0.9166666666666666

In [5]:
# Final Class Prediction
y_pred = model.predict(X_test)

probabilities = model.predict_proba(X_test)

comparison = pd.DataFrame({
    "Actual": y_test.values,
    "Probability": probabilities[:, 1],
    "Prediction": y_pred
})

display(comparison.head(15))

    Actual  Probability  Prediction
0        0     0.357164           0
1        0     0.000039           0
2        0     0.190736           0
3        0     0.005793           0
4        0     0.286925           0
5        1     0.936854           1
6        0     0.176460           0
7        1     0.745851           1
8        1     0.807623           1
9        0     0.000646           0
10       1     0.591709           1
11       0     0.007935           0
12       0     0.061302           0
13       1     0.835979           1
14       0     0.092638           0