## Homework - Problem 21

`svm_data2.csv`를 이용하여 SVM Classification을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- `C=1`

다음 Kernels을 비교한다.

- `linear`
- `poly`
- `rbf`

다음 질문에 답하시오.

- 각 Kernel의 Test Accuracy를 소수점 셋째 자리까지 적으시오.
- 가장 높은 Test Accuracy를 보인 Kernel을 적으시오.

답만 제출하시오.

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC #비선형 분류
from sklearn.svm import LinearSVC #선형 분류
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
df = pd.read_csv('../Input/svm_data2.csv')
display(df.head())

         x1        x2  y
0  0.064786  0.267507  1
1 -0.867799 -0.366626  0
2 -0.533496  0.058780  1
3  0.332655 -0.151100  1
4  0.856088 -0.570838  0

In [7]:
X = df[['x1', 'x2']]
y = df['y']

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((640, 2), (160, 2), (640,), (160,))

In [8]:
kernels = ['linear', 'poly', 'rbf']

acs = pd.DataFrame(columns=['kernel', 'accuracy'])
count = 0

for kernel in kernels:
    model = SVC(kernel=kernel, C=1, random_state=42)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    acs.loc[count] = [kernel, f"{acc:.3f}"]
    count += 1

display(acs)

   kernel accuracy
0  linear    0.562
1    poly    0.644
2     rbf    0.994