## Assignment - 문제 10

`Input/another3_data.csv`를 Train Data와 Test Data로 나누어 Polynomial Regression을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- Polynomial Degree: 2, 4, 6, 8

다음 질문에 답하시오.

- Degree 2 Model의 Train MSE와 Test MSE를 소수점 셋째 자리까지 적으시오.
- Degree 4 Model의 Train MSE와 Test MSE를 소수점 셋째 자리까지 적으시오.
- Degree 6 Model의 Train MSE와 Test MSE를 소수점 셋째 자리까지 적으시오.
- Degree 8 Model의 Train MSE와 Test MSE를 소수점 셋째 자리까지 적으시오.
- 네 Model 중 Test MSE가 가장 작은 Model의 Degree를 적으시오.
- 네 Model 중 Underfitting이 가장 뚜렷한 Model의 Degree를 적으시오.
- 네 Model 중 Overfitting이 가장 뚜렷한 Model의 Degree를 적으시오.

답만 제출하시오.

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [113]:
df = pd.read_csv('../Input/another3_data.csv')

X = df[["x"]]
y = df["y"]

display(df.head())

          x          y
0 -1.003679  10.582890
1  3.605714  21.888364
2  1.855952   9.284877
3  0.789268   7.546605
4 -2.751851   9.966806

In [114]:
degrees = [2,4,6,8]

train_errors = []

for degree in degrees:

    # Polynomial Features 생성
    poly = PolynomialFeatures(
        degree=degree,
        include_bias=False
    )

    X_poly = poly.fit_transform(X)

    # Model Training
    model = LinearRegression()
    model.fit(X_poly, y)

    # Training Data Prediction
    y_pred = model.predict(X_poly)

    # Training Error
    mse = mean_squared_error(y, y_pred)

    train_errors.append(mse)

    print(f"Degree {degree}: MSE = {mse:.3f}")

Degree 2: MSE = 14.970
Degree 4: MSE = 2.055
Degree 6: MSE = 2.038
Degree 8: MSE = 2.032

In [115]:
from sklearn.model_selection import train_test_split

# Train Data와 Test Data 분리
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Total Data:", len(X))
print("Train Data:", len(X_train))
print("Test Data:", len(X_test))

Total Data: 200
Train Data: 160
Test Data: 40

In [116]:
for degree in degrees:        
    poly = PolynomialFeatures(
        degree=degree,
        include_bias=False
    )

    X_train_poly = poly.fit_transform(X_train)
    X_test_poly = poly.transform(X_test)

    # Model Training
    model = LinearRegression()
    model.fit(X_train_poly, y_train)

    # Prediction
    train_pred = model.predict(X_train_poly)
    test_pred = model.predict(X_test_poly)

    # Evaluation
    train_mse = mean_squared_error(y_train, train_pred)
    test_mse = mean_squared_error(y_test, test_pred)

    print(f"Train MSE degree: {degree}:", train_mse)
    print(f"Test MSE degree: {degree}:", test_mse)

Train MSE degree: 2: 14.57959461561239
Test MSE degree: 2: 16.598172869161324
Train MSE degree: 4: 1.961181381279686
Test MSE degree: 4: 2.5122849759610117
Train MSE degree: 6: 1.9351787295489042
Test MSE degree: 6: 2.632594712936303
Train MSE degree: 8: 1.8966240070877411
Test MSE degree: 8: 2.9171421633016674

## Assignment - 문제 11

`Input/another14_data.csv`를 이용하여 Polynomial Regression과 Ridge Regression을 비교한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- Polynomial Degree = 12
- Ridge Regression의 $\alpha = 0.01,\;0.1,\;1,\;10$

다음 질문에 답하시오.

- Regular Linear Regression의 Train MSE와 Test MSE를 소수점 셋째 자리까지 적으시오.
- $\alpha=0.01$인 Ridge Regression의 Test MSE를 소수점 셋째 자리까지 적으시오.
- $\alpha=0.1$인 Ridge Regression의 Test MSE를 소수점 셋째 자리까지 적으시오.
- $\alpha=1$인 Ridge Regression의 Test MSE를 소수점 셋째 자리까지 적으시오.
- $\alpha=10$인 Ridge Regression의 Test MSE를 소수점 셋째 자리까지 적으시오.
- 네 Ridge Models 중 Test MSE가 가장 작은 $\alpha$를 적으시오.
- 위 Model의 가장 큰 Absolute Weight를 소수점 셋째 자리까지 적으시오.

답만 제출하시오.

In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

In [118]:
df = pd.read_csv('../Input/another14_data.csv')

In [119]:
X = df[["x"]]
y = df["y"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

degree = 12
alphas = [0.01, 0.1, 1, 10, 100]

In [120]:
poly = PolynomialFeatures(
    degree=12,
    include_bias=False
)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Linear Regression
linear_model = LinearRegression()
linear_model.fit(X_train_poly, y_train)

# Prediction
train_pred = linear_model.predict(X_train_poly)
test_pred = linear_model.predict(X_test_poly)

print(
    "Train MSE:",
    mean_squared_error(y_train, train_pred)
)

print(
    "Test MSE:",
    mean_squared_error(y_test, test_pred)
)

Train MSE: 54.22476175625893
Test MSE: 43.56128698039559

In [121]:
alphas = [0.01, 0.1, 1, 10, 100]

results = []

model = Ridge()

for alpha in alphas:

    model.set_params(alpha=alpha)
    model.fit(X_train_poly, y_train)

    train_pred = model.predict(X_train_poly)
    test_pred = model.predict(X_test_poly)

    results.append({
        "Alpha": alpha,
        "Train MSE": mean_squared_error(
            y_train,
            train_pred
        ),
        "Test MSE": mean_squared_error(
            y_test,
            test_pred
        )
    })

results = pd.DataFrame(results)

display(results)

    Alpha  Train MSE   Test MSE
0    0.01  54.241392  43.296737
1    0.10  54.756955  42.701407
2    1.00  56.341835  44.180247
3   10.00  61.451229  50.156718
4  100.00  69.379947  49.947195

In [122]:
weights = pd.DataFrame({
    "Feature": [
        f"x^{i}" for i in range(1, degree + 1)
    ],
    "Linear": linear_model.coef_,
    "Ridge": model.coef_
})

display(weights)

   Feature     Linear     Ridge
0      x^1   1.383287  0.330990
1      x^2 -30.722881 -0.842602
2      x^3   3.857540  0.093473
3      x^4  21.203372 -1.028903
4      x^5  -4.256171 -0.111232
5      x^6  -8.034977 -0.767280
6      x^7   1.457483  0.110329
7      x^8   1.622413  0.414278
8      x^9  -0.201506 -0.027069
9     x^10  -0.155739 -0.055222
10    x^11   0.009651  0.001767
11    x^12   0.005675  0.002344

In [123]:
weights["Ridge"].abs().max()

1.028902578550834

## Assignment - 문제 12

`Input/lasso_data2.csv`를 이용하여 Lasso Regression을 수행한다.

다음 조건을 사용한다.

- `test_size=0.2`
- `random_state=42`
- $\alpha = 0.01,\;0.1,\;1$

다음 질문에 답하시오.

- $\alpha=0.01$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=0.1$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=1$일 때 Weight가 0이 아닌 Feature의 수를 적으시오.
- $\alpha=0.1$일 때 Weight가 0인 Feature Name을 모두 적으시오.
- 세 Lasso Models 중 Test MSE가 가장 작은 $\alpha$와 그 Test MSE를 소수점 셋째 자리까지 적으시오.

답만 제출하시오.

In [124]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_squared_error

In [125]:
df = pd.read_csv('../Input/lasso_data2.csv')

In [126]:
X = df.drop(columns=["y"])
y = df["y"]

# Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)



display(df.head())

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,y
0,0.434049,-0.829093,-4.393303,-0.901535,4.588431,-4.722677,-4.568725,-0.441516,3.869059,-0.960351,-34.910058
1,-2.216306,1.955910,4.498369,-2.929594,4.110640,-1.177627,4.268489,-0.697097,-4.386685,0.901040,80.785495
2,-0.754824,-0.751528,1.086590,4.560227,-3.803252,4.532509,-0.703233,-0.943319,-1.327789,-0.009014,-28.781715
3,3.447761,3.581142,1.720027,-0.939888,-3.855314,-2.778015,1.309861,4.463605,3.471495,1.598288,58.161090
4,-4.952811,3.469325,-0.372265,2.168801,4.969650,-1.948739,-4.042762,-3.275777,-0.039060,4.016900,0.301579

In [127]:
linear_model = LinearRegression()

linear_model.fit(
    X_train,
    y_train
)

linear_weights = pd.DataFrame({
    "Feature": X.columns,
    "Weight": linear_model.coef_
})

display(linear_weights)

print(
    "Test MSE:",
    mean_squared_error(
        y_test,
        linear_model.predict(X_test)
    )
)

  Feature    Weight
0      x1  0.104740
1      x2  6.818677
2      x3 -0.173986
3      x4 -5.992371
4      x5  0.171214
5      x6  0.053286
6      x7  8.888501
7      x8 -0.030175
8      x9  0.146533
9     x10  4.061595

Test MSE: 11.721537470003014

In [128]:
alphas = [0.01, 0.1, 1]
# alphas = [0.1]
for alpha in alphas:
    lasso_model = Lasso(
        alpha=alpha
    )

    lasso_model.fit(
        X_train,
        y_train
    )

    lasso_weights = pd.DataFrame({
        "Feature": X.columns,
        "Weight": lasso_model.coef_
    })

    display(lasso_weights)

    print(
        "Test MSE:",
        mean_squared_error(
            y_test,
            lasso_model.predict(X_test)
        )
    )

  Feature    Weight
0      x1  0.102875
1      x2  6.817584
2      x3 -0.172665
3      x4 -5.990788
4      x5  0.170143
5      x6  0.052013
6      x7  8.887027
7      x8 -0.028072
8      x9  0.145564
9     x10  4.060645

Test MSE: 11.719872687760422

  Feature    Weight
0      x1  0.085488
1      x2  6.806844
2      x3 -0.160829
3      x4 -5.976145
4      x5  0.160335
5      x6  0.040541
6      x7  8.873811
7      x8 -0.008842
8      x9  0.137225
9     x10  4.052195

Test MSE: 11.722231406800255

  Feature    Weight
0      x1  0.000000
1      x2  6.718851
2      x3 -0.055387
3      x4 -5.860287
4      x5  0.064901
5      x6  0.000000
6      x7  8.758075
7      x8  0.000000
8      x9  0.041104
9     x10  3.949210

Test MSE: 12.741776587599599